version: '3.8'

volumes:
  redis_data:

network_mode: "host"

services:
  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master
    volumes:
      - redis_data:/data
